#### In Progress
### get verison
http://lein1013.pythonanywhere.com/v1/corona_aut_api/versionnr
#### Working
### Get Source
http://lein1013.pythonanywhere.com/v1/corona_aut_api/source

### Get Data
http://lein1013.pythonanywhere.com/v1/corona_aut_api/data
###
http://lein1013.pythonanywhere.com/v1/corona_aut_api/warnregionname/Bezirk/Eisenstadt(Stadt)
### 
http://lein1013.pythonanywhere.com/v1/corona_aut_api/warnregionname/Bezirk/Jennersdorf
# soll 105
###
http://lein1013.pythonanywhere.com/v1/corona_aut_api/warnregionname/Bezirk/Steyr(Stadt)
###
http://lein1013.pythonanywhere.com/v1/corona_aut_api/warnname/Steyr(Stadt)
###
http://lein1013.pythonanywhere.com/v1/corona_aut_api/warnname/Steyr
###
http://lein1013.pythonanywhere.com/v1/corona_aut_api/warngkz/5
###
http://lein1013.pythonanywhere.com/v1/corona_aut_api/warngkz/80301

