#### local api urls

### Get source url
http://127.0.0.1:5000/v1/corona_aut_api/source

### Get the json data from source
http://127.0.0.1:5000/v1/corona_aut_api/data

### Get Data by Name
http://127.0.0.1:5000/v1/corona_aut_api/name/Linz

### Request with GKZ code
http://127.0.0.1:5000/v1/corona_aut_api/gkz/10308

### Get last update time (download of full dataset)
http://127.0.0.1:5000/v1/corona_aut_api/updatetime 

### Get the current server time
http://127.0.0.1:5000/v1/corona_aut_api/time

### Get a configuration example for homeassistant
http://127.0.0.1:5000/v1/corona_aut_api/homeassistant

### root folder 
http://127.0.0.1:5000/
