#### local api urls
### get verison
http://127.0.0.1:5000/v1/corona_aut_api/source
#### Working
### Get Source
http://127.0.0.1:5000/v1/corona_aut_api/data

### Get Data
http://127.0.0.1:5000/v1/corona_aut_api/name/Steyr
###
http://127.0.0.1:5000/v1/corona_aut_api/gkz/10308
### 
